# Generated by Django 5.2.8 on 2025-11-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0002_alter_ticket_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="user",
        ),
    ]
