# Generated by Django 5.2.8 on 2025-11-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_remove_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='winningresult',
            name='prize',
            field=models.BigIntegerField(default=0),
        ),
    ]
