# Generated by Django 5.2.8 on 2025-11-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_winningresult_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winningresult',
            name='prize',
        ),
    ]
